-- Wholesale-buy domain rebuild: CREATED→CONFIRMED→PAID→RECEIVED→CHECKED plus the failure
-- branches, dual purity pricing, delivered-weight capture and the edit-window deadline.
--
-- Generated by drizzle-kit, then hardened by hand so it also applies to a populated table:
-- the legacy statuses are remapped while the column is text, and the two new NOT NULL columns
-- are added nullable, backfilled, then constrained.

ALTER TABLE "whole_buy_statuses" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ALTER COLUMN "current_status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ALTER COLUMN "current_status" SET DEFAULT 'CREATED'::text;--> statement-breakpoint

-- legacy status remap, done while both columns are plain text:
--   DRAFT   → CREATED  (old system status 1)
--   SETTLED → CHECKED  (the old terminal state; inventory had already moved by then)
UPDATE "whole_buy_statuses" SET "status" = 'CREATED' WHERE "status" = 'DRAFT';--> statement-breakpoint
UPDATE "whole_buy_statuses" SET "status" = 'CHECKED' WHERE "status" = 'SETTLED';--> statement-breakpoint
UPDATE "whole_buy_transactions" SET "current_status" = 'CREATED' WHERE "current_status" = 'DRAFT';--> statement-breakpoint
UPDATE "whole_buy_transactions" SET "current_status" = 'CHECKED' WHERE "current_status" = 'SETTLED';--> statement-breakpoint

DROP TYPE "public"."whole_buy_status";--> statement-breakpoint
CREATE TYPE "public"."whole_buy_status" AS ENUM('CREATED', 'CONFIRMED', 'PAID', 'RECEIVED', 'CHECKED', 'PAYMENT_FAILED', 'DISPUTED', 'CANCELLED', 'REJECTED', 'RETURNED');--> statement-breakpoint
ALTER TABLE "whole_buy_statuses" ALTER COLUMN "status" SET DATA TYPE "public"."whole_buy_status" USING "status"::"public"."whole_buy_status";--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ALTER COLUMN "current_status" SET DEFAULT 'CREATED'::"public"."whole_buy_status";--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ALTER COLUMN "current_status" SET DATA TYPE "public"."whole_buy_status" USING "current_status"::"public"."whole_buy_status";--> statement-breakpoint

-- price_per_gb keeps its name and its meaning: the 96.5% quote. The 99.9% quote is derived from
-- it by the purity ratio for any pre-existing row; from here on the operator enters it.
ALTER TABLE "whole_buy_transactions" ADD COLUMN "price_per_gb_999" numeric;--> statement-breakpoint
UPDATE "whole_buy_transactions" SET "price_per_gb_999" = "price_per_gb" * (99.9 / 96.5) WHERE "price_per_gb_999" IS NULL;--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ALTER COLUMN "price_per_gb_999" SET NOT NULL;--> statement-breakpoint

-- delivered weight — null until the shipment is checked, and null when it matched the order
ALTER TABLE "whole_buy_transactions" ADD COLUMN "actual_weight_gb" numeric;--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ADD COLUMN "actual_weight_gm" numeric;--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ADD COLUMN "actual_amount" numeric;--> statement-breakpoint

-- edit window deadline; pre-existing rows are past theirs by definition
ALTER TABLE "whole_buy_transactions" ADD COLUMN "confirm_due_at" timestamp;--> statement-breakpoint
UPDATE "whole_buy_transactions" SET "confirm_due_at" = "recorded_at" WHERE "confirm_due_at" IS NULL;--> statement-breakpoint
ALTER TABLE "whole_buy_transactions" ALTER COLUMN "confirm_due_at" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "whole_buy_transactions" ADD COLUMN "notes" text;
